### ISSUE TITLE
Error Invalid handler specified

### ISSUE THREAD

**Issue by tjorim** [ITSpecialist111/ai_automation_suggester#1]
Downloaded through HACS and restarted HA.
When trying to set it up I get the following pop-up:
```
Error
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

**Comment by ITSpecialist111** [comment]
Thank you for raising. Issue was to do a domain name change in the const.py from "ai_suggester" to "ai_automation_suggester". Please uninstall from Hacs and redownload this has been updated in Github

**Comment by ITSpecialist111** [comment]
After submitting V1.0 through the HACS checks today and updating the naming convention, the Domain changes within the Const.py also needed to be changed as referenced in the code. Code Updated Accordly.

**Comment by tjorim** [comment]
FYI, there was no new release so nothing to update in HACS. I made the changes locally and getting another error. Thanks for the help!
