### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by Bytelink5616** [ITSpecialist111/ai_automation_suggester#11]
I am not sure this is an issue as against an error on my behalf.  I have got the message that there are suggestions available but when I try to find them there are none to display.  Also in the logs I get the following error
 
This error originated from a custom integration.

Logger: custom_components.ai_automation_suggester.coordinator
Source: custom_components/ai_automation_suggester/coordinator.py:137
integration: AI Automation Suggester (documentation, issues)
First occurred: October 28, 2024 at 4:21:32 PM (1 occurrences)
Last logged: October 28, 2024 at 4:21:32 PM

Error communicating with OpenAI: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-proj-********************************************************************************************************************************************************yhQA. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

I changed the API key in the integration to reflect the correct one.  Prior to this I had entered the one being displayed here.  I then deleted it in OpenAI as I thought it was the problem and created a new one but it would appear it is still trying to use the old one.  By the way thanks for the integration.

**Comment by flyingtech** [comment]
I am getting the same error also. 🤷‍♂️

**Comment by ITSpecialist111** [comment]
Thank you for bringing this to my attention. Simple checks are performed on the key before setting up the integration. Previous versions, such as v1.04, had more complex checks that caused issues.

Please ensure that you have version 1.06 installed. Here are the steps to follow:

1. Remove the custom integration:
   - Open the file editor or Visual Studio Code.
   - Navigate to Custom Components.
   - Delete the entire 'ai_automation_suggester' folder.

2. Restart Home Assistant.

3. Reinstall the integration via HACS, making sure that version 1.06 is selected. Download it, and then restart Home Assistant once again.

If you still encounter issues, please send me the logs, and I'll take a look.
