### ISSUE TITLE
Error creating notification: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by Jord38** [ITSpecialist111/ai_automation_suggester#22]
Just found out about this amazing integration and wanted to try it out, using OpenAI with the default gpt-4o-mini model just to test it I entered my API key setup the integration only for nothing to happen afterwards, thought I was supposed to get some sort of notification message with suggestions but upon opening the integration saw the error status. So enabled debug logging and got the error log attached.
Have left out some details like entities and attributes
[home-assistant_ai_automation_suggester_2024-11-01T17-35-10.732Z.log](https://github.com/user-attachments/files/17602655/home-assistant_ai_automation_suggester_2024-11-01T17-35-10.732Z.log)

Let me know if there is any more information I can provide that I have missed

**Comment by ITSpecialist111** [comment]
Thank you for taking the time to feedback. I understand the issue. I've seen this in testing before the release of V1.07. Could I kindly ask for you to delete the integration, and manually remove through file editor -> custom components. Reinstall via HACS and restart.

**Comment by thelastoth** [comment]
Hi, i have the same issue and after following the instructions above, now i keep geeting "error" in the integration diagnostic

**Comment by JonseyFTW** [comment]
Had the same issue where it was configured, no errors, but never got a notification for the automations. Downgraded back to 1.6 and it worked and got the notification

**Comment by ITSpecialist111** [comment]
It seems that adding new models has caused some issues. Version 1.06 is working well for OpenAI. I will continue working on this over the weekend.

**Comment by ITSpecialist111** [comment]
Updated to resolve issues within this pull request:  https://github.com/ITSpecialist111/ai_automation_suggester/releases/tag/V1.08

**Comment by tjorim** [comment]
@ITSpecialist111, issue still exists on 1.1.1:

```
This error originated from a custom integration.

Logger: custom_components.ai_automation_suggester.coordinator
Source: custom_components/ai_automation_suggester/coordinator.py:171
integration: AI Automation Suggester (documentation, issues)
First occurred: 17:39:08 (4 occurrences)
Last logged: 17:46:55

Error creating notification: object NoneType can't be used in 'await' expression
```
