### ISSUE TITLE
Mismatching Attributes vs. History/Logbook

### ISSUE THREAD

**Issue by ShadyBrk** [ITSpecialist111/ai_automation_suggester#23]
When viewing the sensor attribute details, the logbook/history results do not match. Attributes states: "No suggestions available", but History/Logbook states: "Suggestions available"

Using OpenAI API.

![2024-11-01_13-42-41](https://github.com/user-attachments/assets/eee3c184-cd75-45f2-9db0-83d26ab3758f)

**Comment by Wh1t3Rose** [comment]
I have the same problem. Just installed the integration for the first time 20 minutes ago

**Comment by Wh1t3Rose** [comment]
I switched from OpenAI to my own self-hosted Ollama instance. Same issue still

**Comment by CarstenDennis** [comment]
I see the same - installed the integration today.

Note - running Home Assistant in a docker setup if that makes a difference?

![billede](https://github.com/user-attachments/assets/6749f5c3-825e-42a5-a965-cf7000759b22)

**Comment by ITSpecialist111** [comment]
This issue seems to be intermittent. I've reworked the code in version 1.08 to address this. Please update to version 1.08. Updated to resolve issues within this pull request: https://github.com/ITSpecialist111/ai_automation_suggester/releases/tag/V1.08
