### ISSUE TITLE
skip ignore some suggestions possible?

### ISSUE THREAD

**Issue by remb0** [ITSpecialist111/ai_automation_suggester#24]
action: ai_automation_suggester.generate_suggestions
data:
  provider_config: my_provider_chatgpt
  custom_prompt: skip notifications about updates

but I got still a bunch of notifications about update notifications or auto updating addons.
do I something wrong?

**Comment by ITSpecialist111** [comment]
The main issue is that the integration was initially designed to focus on 'new' entities and provide examples related to them. There have been requests to make this functionality more flexible, which will be addressed in Version 2 of this custom integration. I have been working diligently to establish the foundational elements for multiple providers and local LLMs to improve suggestions like these.

Let's troubleshoot the problems you are experiencing in Version 1.08 and see if we can recreate the issue so we can work on it for Version 2. see if we can recreate the issue so we can work on it for Version 2.

**Comment by remb0** [comment]
If I can help to deliver info please let me know!

**Comment by ITSpecialist111** [comment]
Are you expecting the custom prompt to not generate notifications for that one call or for all calls?

**Comment by remb0** [comment]
Great!   thank you so much!  I gonna test this! :)
