### ISSUE TITLE
Can't generate Suggestions

### ISSUE THREAD

**Issue by chrisgwynne** [ITSpecialist111/ai_automation_suggester#29]
I get the error of;

 Detected that custom integration 'ai_automation_suggester' calls async_forward_entry_setup for integration, ai_automation_suggester with title: AI Automation Suggester (OpenAI) and entry_id: 01JBW14K2WWG3Z04EHPY9XZWDP, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/ai_automation_suggester/__init__.py, line 110: await hass.config_entries.async_forward_entry_setup(entry, platform), please create a bug report at https://github.com/ITSpecialist111/ai_automation_suggester/issues

**Comment by ITSpecialist111** [comment]
From the error it looks like it might be looking at an old provider setting. Can you please try: 

Remove all configured AI providers from the integration
Uninstall the integration completely
Restart Home Assistant
Reinstall the integration
Reconfigure your AI providers
This clean installation approach will ensure a fresh start if the migration process encounters any critical issues.

**Comment by ITSpecialist111** [comment]
Following the steps above will resolve these issues

**Comment by tjorim** [comment]
@ITSpecialist111, I did those steps but also getting this error:

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:189
First occurred: 17:58:18 (1 occurrences)
Last logged: 17:58:18

Detected that custom integration 'ai_automation_suggester' calls async_forward_entry_setup for integration, ai_automation_suggester with title: AI Automation Suggester (OpenAI) and entry_id: 01JC8XSEH6TEWSDEQ8E1RXYHYM, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/ai_automation_suggester/__init__.py, line 110: await hass.config_entries.async_forward_entry_setup(entry, platform), please create a bug report at https://github.com/ITSpecialist111/ai_automation_suggester/issues
```

**Comment by tjorim** [comment]
Looks like the code is still there in the release: https://github.com/ITSpecialist111/ai_automation_suggester/tree/1.1.1
