### ISSUE TITLE
How to use xAI's Grok?

### ISSUE THREAD

**Issue by Noobeley** [ITSpecialist111/ai_automation_suggester#32]
I got some free credits for xAI and thus have an API key, but it keeps saying API Error occured no matter what AI Provider I put, and xAI/Grok is not an option. Is it just incompatible?

**Comment by ITSpecialist111** [comment]
The API calls are there; however, not all API errors will come through within the integrations UI.

Can you try again, then check the HASS system logs for specific error messages and post them here, please?

**Comment by ITSpecialist111** [comment]
Closing as no response
