### ISSUE TITLE
You exceeded your current quota

### ISSUE THREAD

**Issue by ward0** [ITSpecialist111/ai_automation_suggester#36]
Situation:

I created a new API key on https://platform.openai.com/ just to be sure.
In logging I get:

Logger: custom_components.ai_automation_suggester.coordinator
Source: custom_components/ai_automation_suggester/coordinator.py:291
integration: AI Automation Suggester ([documentation](https://github.com/ITSpecialist111/ai_automation_suggester), [issues](https://github.com/ITSpecialist111/ai_automation_suggester/issues))
First occurred: 3:17:07 PM (3 occurrences)
Last logged: 4:46:04 PM

OpenAI API error: { "error": { "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.", "type": "insufficient_quota", "param": null, "code": "insufficient_quota" } }

Logger: custom_components.ai_automation_suggester.coordinator
Source: custom_components/ai_automation_suggester/coordinator.py:180
integration: AI Automation Suggester ([documentation](https://github.com/ITSpecialist111/ai_automation_suggester), [issues](https://github.com/ITSpecialist111/ai_automation_suggester/issues))
First occurred: 3:17:07 PM (3 occurrences)
Last logged: 4:46:04 PM

No valid suggestions received from AI

On openai.com usage site I have last key used: never.

**Comment by ITSpecialist111** [comment]
Issue with no API funds on your account. Please add monies

Error: You exceeded your current quota, please check your plan and billing details
