### ISSUE TITLE
[feature request] allow to disable scan frequency

### ISSUE THREAD

**Issue by tjorim** [ITSpecialist111/ai_automation_suggester#4]
It's not possible to disable the automatic scan frequency. Allow config value to be set to 0 to disable the refresh.

**Comment by ITSpecialist111** [comment]
Hi @tjorim,

Thank you for your valuable feedback! 😊

I’m happy to let you know that in the latest release (v1.04), we’ve implemented exactly what you suggested. You can now set the scan_frequency to 0 to completely disable the automatic refresh. This gives you full control to manually trigger automation suggestions whenever you need them via Developer Tools -> Actions.

Thanks again for your suggestion—it’s helped make the integration even more flexible and user-friendly. If you have any more feedback or encounter any issues, feel free to reach out!
