### ISSUE TITLE
"State attributes exceed maximum size of 16384 bytes"

### ISSUE THREAD

**Issue by Wendelstein7** [ITSpecialist111/ai_automation_suggester#8]
_Thanks for all the hard work on this amazing integration! I can see great future possibilities, the roadmap and enthusiasm put into this seem very promising :)_

When having a decently sized Home Assistant setup, the A.I.-agent can suggest quite a few automations. The list of this automations may be of such size, that the recorder complains about exceeding a (default) maximum size for state attributes.

```
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:624
integration: Recorder ([documentation](https://www.home-assistant.io/integrations/recorder), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+recorder%22))
First occurred: 15:25:21 (2 occurrences)
Last logged: 15:25:21

State attributes for sensor.ai_automation_suggestions exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
```

Perhaps we need to think about a future-proof way to store the result of the generated suggestions. While it is not a breaking _problem_ that the entity attributes will not be stored, one could assume that it is not an ideal way to (ab)use attributes. At this moment, for example the template `{{ state_attr("sensor.ai_automation_suggestions", "suggestions") }}` results in an output length of 34621 characters for me, exceeding the 16 kB default limit for the recorder.

**Comment by ITSpecialist111** [comment]
Updated to resolve issues within this next version V1.08. Please read:  https://github.com/ITSpecialist111/ai_automation_suggester/releases/tag/V1.08
