### ISSUE TITLE
Output is cut-off due to a token limit

### ISSUE THREAD

**Issue by Wendelstein7** [ITSpecialist111/ai_automation_suggester#9]
There's [a hard-coded token limit of 500 tokens](https://github.com/ITSpecialist111/ai_automation_suggester/blob/0a43bda4c5bcc4141d280d082d0556f2d4b81ee6/custom_components/ai_automation_suggester/coordinator.py#L130) in the current version of the integration. For reasonably large Home Assistant setups where more than 10 suggestions are being generated this causes the suggestion output to be cut-off:

![image](https://github.com/user-attachments/assets/2363410c-61b5-44d6-9313-246806966df4)

The limit of the model currently in use (gpt-4o-mini) is 16384 tokens. At the moment of writing, gpt-4o-mini costs $0.600 / 1M output tokens. This means that a maximum usage of 16384 tokens would cost $0.009 per prompt, which I think is not unreasonable or unresponsible to set as an output limit.

In the future it would be nice if both the model and the maximum token length are user-configurable values. I do not know how to code that (yet), but I created a pull-request to increase the token limit to 16384 for now: PR https://github.com/ITSpecialist111/ai_automation_suggester/pull/10

**Comment by ITSpecialist111** [comment]
Thank you. I am investigating the limits and evaluating more suitable options that will provide additional information and streamline the automation that may be important for the individual. I will add this to the urgent list.

**Comment by ITSpecialist111** [comment]
Updated to resolve issues within this next version, please read:  https://github.com/ITSpecialist111/ai_automation_suggester/releases/tag/V1.08
